### ISSUE TITLE
Github markdown

### ISSUE THREAD

**Issue by cozzyy2002** [cozzyy2002/MyMusic#1]
This issue is exercise of Github markdown.

- References
  - [どうしてみんなMarkdown書くときTypora使わないの? - Qiita](https://qiita.com/AnchorBlues/items/532dba54cd2f0465af97?utm_source=Qiita%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9&utm_campaign=39ed5c766c-Qiita_newsletter_337_11_14_2018&utm_medium=email&utm_term=0_e44feaa081-39ed5c766c-34094477)
  - [Markdown Reference - typora](https://support.typora.io/Markdown-Reference/)
  - [Writing on GitHub](https://help.github.com/articles/github-flavored-markdown/)

Welcome to the MyMusic wiki![^footnote]

[^footnote]: Here is the *text* of the ***footnote***.

### Task list
- [ ] Task list items
  - sub item.
- [x] able to be ordered
- [ ] are
- [ ] by dragging a handle left most.
  - Note

| header 1 | Center | Header 2 |
| -------- | :----: | --------: |
|name      | 〇     | 20      |
|abc       | ✖     | 100 |

1. Numbered list
   * Unnumbered list
   * next
     * More nested item.
1. Next Numbered item.
   * [1_IdolCollection.list](../blob/master/1_IdolCollection.list)
